apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    target port: 8080
    protocol: TCP
  type: LoadBalancer
  
